### ISSUE TITLE
Mac OSX Monterey security

### ISSUE THREAD

**Issue by AX-LLaidley** [mb21/panwriter#110]
Hi there,

I commented on #33 as this seems to be related. When I try to use PanWriter on Monterey, I get a message that macOS can't verify that the application doesn't contain malware, and the only options given are to cancel or move the app to Trash. I'm unable to run the app as it stands. 

Are there plans to fix this in the near future?

**Comment by mb21** [comment]
you should be able to "right-click -> open" on the app, then confirm again in the dialog. You only have to do that once.

**Comment by mjgardner** [comment]
> you should be able to "right-click -> open" on the app, then confirm again in the dialog. You only have to do that once.

Thanks for confirming you're an unserious developer.

Just sign and notarize the damn app.

**Comment by mb21** [comment]
closing in favour of https://github.com/mb21/panwriter/issues/33
