### ISSUE TITLE
Takes over DOCX default without asking

### ISSUE THREAD

**Issue by dmonder** [mb21/panwriter#112]
Just installed PanWriter only to discover it takes over the DOCX (and probably other) default for Windows 10 without ever asking me if that was OK. It was definitely not OK. I plan to use these side by side and should have the option to do so. Now I have to go through and fix all my defaults back to the original program. Please add a prompt before making this change.

**Comment by mb21** [comment]
does this also happen on Windows 11? I'm not sure what electron builder does exactly on windows... PanWriter just uses this: https://www.electron.build/configuration/configuration.html#PlatformSpecificBuildOptions-fileAssociations

**Comment by dmonder** [comment]
Yes, this also happens on Windows 11.

**Comment by dmonder** [comment]
Maybe you can add an option to the install process for the user to choose to add file associations or not?

**Comment by mb21** [comment]
ah, we already have an issue for this, closing in favour of https://github.com/mb21/panwriter/issues/31
