### ISSUE TITLE
Export problem with AppImage 0.8.4 on Linux Slackware

### ISSUE THREAD

**Issue by fhouweli** [mb21/panwriter#114]
Hi,
when trying to export my document to html, the pandoc command has an empty --to argument (and therefore --standalone is interpreted as a format.
![Screenshot_2022-08-26_19-30-52](https://user-images.githubusercontent.com/67115392/186960679-f2182de5-25d5-49c9-8ada-b826d4f49c69.png)

**Comment by mb21** [comment]
I cannot reproduce... what's the exact input you were using?

**Comment by fhouweli** [comment]
Thanks for looking into it. My working file is called "sql.md". When I 
choose "Export..." a dialog opens with "sql" in the "Name" field 
(highlighted/selected) and "HTML" in the select box below. Changing the 
file format with the select box does not add an extension in the "Name" 
input field. Pressing "Export" causes the error. **HOWEVER**, if I 
manually add ".html" to the filename, the export succeeds!

It is just a problem of the (stupid?) user thinking the file extension 
would be added automatically.

I really enjoy using PanWriter.

Regards

frans

**Comment by mb21** [comment]
> Changing the file format with the select box does not add an extension in the "Name" input field.

that's odd. because it does for me on macOS. are you on the latest PanWriter version?

can you reproduce on other linux distros?

**Comment by mbozkurt** [comment]
I am on latest Panwriter and I can confirm same problem exists Mint Linux 19.3.

**Comment by mb21** [comment]
hm.. we're just [using](https://github.com/mb21/panwriter/blob/master/electron/pandoc/export.ts#L38) electron's [dialog.showSaveDialog](https://www.electronjs.org/docs/latest/api/dialog#dialogshowsavedialogbrowserwindow-options) `filters` option.

you're saying only the default name is missing the html extension (that we could probably fix in PanWriter)? And when you switch to an other format in the dropdown the extension is added?

**Comment by mb21** [comment]
uh, that seems like an Electron bug then, because all we get back is the `filePath`, so if that doesn't change when you change the dropdown, there's nothing we can do in PanWriter to fix it... 

I'll try to update to the newest Electron version soonish... maybe they have fixed it already...

**Comment by hwpf** [comment]
got exactly the same issue with panwriter 0.8.4 freshly installed at Manjaro Linux ... none of the formats can be exported. Will it be posted here, when a fix is available?

**Comment by Merga189** [comment]
Same here.

Debian 12 bookworm with Appimage 0.8.6 and pandoc 2.17.1.1 (Debian source)

![Screenshot_2024-07-11_19-25-29](https://github.com/mb21/panwriter/assets/166748464/d0974c84-2fef-4e14-adef-03186aaa2a7d)

**Comment by mb21** [comment]
Can somebody confirm this happens only when using the AppImage? What happens if you [run the development version](https://github.com/mb21/panwriter?tab=readme-ov-file#develop)?

**Comment by mb21** [comment]
btw. from above in this thread:

> Changing the file format with the select box does not add an extension in the "Name" input field. Pressing "Export" causes the error. **HOWEVER**, if I
manually add ".html" to the filename, the export succeeds!

That's still a viable workaround, right?

**Comment by mb21** [comment]
Okay, I found the [relevant Electron issue](https://github.com/electron/electron/issues/21935). Apparently, that's just not something Electron supports on Linux, which is a bummer.

But from above in this thread:

> Changing the file format with the select box does not add an extension in the "Name" input field. Pressing "Export" causes the error. **HOWEVER**, if I
manually add ".html" to the filename, the export succeeds!

That's still a viable workaround, right? So perhaps we should just remove the selector dropdown on Linux to avoid confusion?

**Comment by mb21** [comment]
I implemented this approach in a draft PR: https://github.com/mb21/panwriter/pull/166

Can anybody test this on Linux? Check out that branch and see https://github.com/mb21/panwriter/#develop

**Comment by mb21** [comment]
I've merged this to the `master` branch. But apparently my friend's Apple Developer Certificate is expired so I cannot make a release. Perhaps the day has come I'll have to fork over 100.- to Apple 🙄 

Anyway, for now, here's [the Linux AppImage](https://we.tl/t-TzOlfYZRxA).

**Comment by Merga189** [comment]
First of all thank you for reacting.

Now I have both appimages here on my Debian 12.

0.8.7 is working now and I can convert a *.md to *.odt

![Screenshot_2024-07-14_13-05-25](https://github.com/user-attachments/assets/e58a380e-9914-4021-8ec7-cf4f65ed1e46)

But here a screenshot with 0.8.6 with a possibility to select the file extension

![Screenshot_2024-07-14_12-58-18](https://github.com/user-attachments/assets/78d443ef-770c-4574-86fd-ddcbdc31a561)

and now 0.8.7, where that possibilty is missing.

![Screenshot_2024-07-14_13-00-32](https://github.com/user-attachments/assets/767c5277-5a50-41b4-823f-9c429a1c714c)

br Karl

**Comment by mb21** [comment]
@Merga189 thanks, yes. on Linux that electron-provided dropdown apparently isn't working correctly, so the only thing I could think of was to remove it. Instead, you just have to write the filename including extension.
