### ISSUE TITLE
Linux AppImage: ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.

### ISSUE THREAD

**Issue by akwala** [mb21/panwriter#116]
This happens when I try to launch the AppImage. It hangs without showing the window, does not exit.

```
$ /home/user/Applications/PanWriter-0.8.4_e892e0f135d23cc0b17564455c987916.AppImage --no-sandbox
Error loading or parsing YAML file.ENOENT: no such file or directory, open '/home/user/.config/PanWriterUserData/settings.yaml'
Checking for update
[18789:1005/004805.023111:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
Update for version 0.8.4 is not available (latest version: 0.8.4, downgrade is disallowed).
checkForUpdatesAndNotify called, downloadPromise is null
```
Operating System: Kubuntu 22.04
KDE Plasma Version: 5.24.6
KDE Frameworks Version: 5.95.0
Qt Version: 5.15.3
Kernel Version: 5.15.0-46-generic (64-bit)
Graphics Platform: X11
Graphics Processor: Mesa Intel® Xe Graphics

**Comment by mb21** [comment]
Hm... I don't know much about appimages... perhaps updating to the latest Electron version would help... happy to accept a pull request!

**Comment by akwala** [comment]
The reported `ERROR:sandbox_linux.cc(377)` might be misleading. It was also reported when I ran Panwriter in development mode from the source, but it didn't keep Panwriter from launching:
```
10:16:55 PM - Starting compilation in watch mode...
[1] 
[0] No issues found.
[2] Error loading or parsing YAML file.ENOENT: no such file or directory, open '/home/user/.config/PanWriterUserData/settings.yaml'
[2] [18538:1008/221701.401643:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
[2] APPIMAGE env is not defined, current application is not an AppImage
[2] no recentFiles found? [Error: ENOENT: no such file or directory, open '/home/user/.config/PanWriter/recentFiles.json'] {
[2]   errno: -2,
[2]   code: 'ENOENT',
[2]   syscall: 'open',
[2]   path: '/home/user/.config/PanWriter/recentFiles.json'
[2] }
[1] 
[1] 10:17:02 PM - Found 0 errors. Watching for file changes.
```

**Comment by mb21** [comment]
So it works when building from source but not when running from the appimage?

**Comment by akwala** [comment]
> So it works when building from source but not when running from the appimage?

Panwriter launches in dev mode, as expected, when I do `yarn run electron:dev`.

`ERROR:sandbox_linux.cc(377)` did _not_ happen with `"electron-builder": "^23.6.0"` in `"devDependencies"` in `package.json`. However, this didn't fix the AppImage issue, nor did `"electron": "^21.0.1"`.

I posted a [question in the AppImage image forum](https://discourse.appimage.org/t/debugging-an-appimage-that-does-not-launch/2849?u=4slam.) over week ago, no responses so far

**Comment by mb21** [comment]
Somebody [reported the newest version works on Ubuntu](https://github.com/mb21/panwriter/issues/173#issuecomment-2323941225). So probbly it works on Kubuntu now as well. Let us know if not, then we can reopen this issue.

**Comment by akwala** [comment]
> Somebody [reported the newest version works on Ubuntu](https://github.com/mb21/panwriter/issues/173#issuecomment-2323941225). So probbly it works on Kubuntu now as well. Let us know if not, then we can reopen this issue.

Yes, v.0.8.6 AppImage does launch as expected in Kubuntu 22.04.

Thanks.
