### ISSUE TITLE
Editing CSS makes text disappear

### ISSUE THREAD

**Issue by insanerwayner** [mb21/panwriter#12]
On Windows 10:

1. Create some text 
2. Click **Add CSS Style** 
3. Make any change to CSS
4. Text disappears in preview.  

Even if you change the CSS back to it's original state, the preview will not generate.

**Comment by mb21** [comment]
Seems that the update to electron v4 broke this, and I didn't notice! We get `overflow on page-1` from paged.js.

Interestingly, opening a file is still fine... just editing breaks the paginated preview. The normal preview is also fine, switching back to that, if you don't need the pages, is a workaround for now I suppose...
