### ISSUE TITLE
TOC? 

### ISSUE THREAD

**Issue by Skeeve** [mb21/panwriter#130]
I'm trying to convince colleagues that Markdown would be a fantastic format for most of our documents since we can use pandoc to convert to any end format we might want and consistently get output conforming to our standards.

In order for them to not have to use any simple text editor and wonder what the output might look like, I thought panwriter would be a good way for them to get used to markdown.

But I'm currently wondering, when saving to (e.g.) PDF, how to get a table of contents. I can see no option when exporting in panwriter to get pandoc to create a toc.

**Comment by mb21** [comment]
From https://panwriter.com/MANUAL.html#export-via-pandoc:

```
---
output:
  latex:
    toc: true
---
```

**Comment by Skeeve** [comment]
Cool! Thanks a lot!
