### ISSUE TITLE
Feature request: do not force to auto update the application (Mac)

### ISSUE THREAD

**Issue by ruda** [mb21/panwriter#139]
I (re)installed PanWriter `0.8.4` in an old MacBook running OS X El Capitan (macOS 10.11.6) and the application tries automatically to upgrade to version `0.8.5` which is not compatible to El Capitan. Is there any way to stop this to happens? Also, upgrades should be an opt-in.

https://github.com/mb21/panwriter/blob/f68ea9d9779ab55597cf838bd137bb35ba2b5647/electron/main.ts#L199

**Comment by mb21** [comment]
Hello, this is actually already implemented! See https://panwriter.com/MANUAL.html#settings

**Comment by ruda** [comment]
Thank you! I didn't notice the manual online :)
