### ISSUE TITLE
Respect @Page size declaration

### ISSUE THREAD

**Issue by typometre** [mb21/panwriter#14]
Panwriter doesn't seems to respect the size delcared in YAML frontmatter. 
Telling
``` 
@page {
    size: A5 portrait;
  }
````
or even with `148mm 210mm`
doesn't work.

It works in User Data file but not directly in the file itlself

**Comment by mb21** [comment]
Can you post the whole editor contents? Try the `Format` -> `Add CSS style` menu item on an empty document.

Also: make sure you're on PanWriter 0.6.3

**Comment by mb21** [comment]
Let me know if you still think there's a bug... closing for now.
