### ISSUE TITLE
default.yaml in "...AppData\Local\PanWriterUserData" is not used

### ISSUE THREAD

**Issue by micha06de** [mb21/panwriter#164]
I wanted to add my own formatting to my document and therefore created a folder "PanWriterUserData" in "...AppData\Local" as described in the manual, in which I created a file "default.yaml" with the corresponding styles as described in the section "Default CSS and YAML". Unfortunately this does not work, it looks as if the YAML file is not read at all. 

What am I doing wrong?

**Comment by mb21** [comment]
What OS are you on? PanWriter is calling [electron's `app.getPath('appData')`](https://www.electronjs.org/docs/latest/api/app#appgetpathname) under the hood.

**Comment by micha06de** [comment]
The OS is Windows 10. "%APPDATA%" points to "...\AppData\Roaming" (the manual says "...\AppData\Local") so I copied the folder "PanWriterUserData" to "...\AppData\Roaming" as a test - it still doesn't work. I can enter whatever I want in the "default.yaml" (e.g. "title"), but nothing happens.

**Comment by micha06de** [comment]
Now it works under Windows. The "PanWriterUserData" folder must be created under "...\AppData\Roaming". **And there should be no '---' at the beginning and end of the YAML file**. However, if the formatting is to be retained when exporting to HTML, there should not be an embedded style section in the YAML area of the Markdown, as this overwrites the definitions from default.yaml.

**Comment by mb21** [comment]
Thanks, I changed it in the manual: https://github.com/mb21/panwriter/commit/275015597125293144d899f28679e62cac4f647d
I still have to publish to website, but closing this issue then.
