### ISSUE TITLE
Cannot be launched at ubuntu 22.04

### ISSUE THREAD

**Issue by herrdeh** [mb21/panwriter#173]
Thank you for providing panwriter.
This is what happens at ubuntu 22.04, snap package panwriter 0.6.3 rev.13:

`$ panwriter
Gtk-Message: 11:22:56.287: Failed to load module "xapp-gtk3-module"
Gtk-Message: 11:22:56.288: Failed to load module "appmenu-gtk-module"

(panwriter:12471): Gtk-WARNING **: 11:22:56.322: Theme parsing error: gtk.css:3536:25: 'font-feature-settings' is not a valid property name
SNAP env is defined, updater is disabled
`
Nothing more happens, no windows opens etc.
Any advice would be appreciated.

**Comment by mb21** [comment]
Not sure where you got that SNAP build but I think the AppImage should work? https://github.com/mb21/panwriter/releases/download/v0.8.5/PanWriter-0.8.5.AppImage

**Comment by herrdeh** [comment]
Your appimage works. 
That snap came from ubuntu "snap store". I filed a bug [HERE](https://bugs.launchpad.net/ubuntu/+source/snap/+bug/2078662) but I'm in doubt they'll work on it as I cannot file it against package panwriter.
