### ISSUE TITLE
Open Recent menu doesn't show recent documents

### ISSUE THREAD

**Issue by AdamIsrael** [mb21/panwriter#18]
Version: 0.6.3 (AppImage)

The File -> Open Recent menu doesn't show after the application is restarted.

Steps to reproduce:

1. Open PanWriter
2. Open a Markdown file
3. Close PanWriter
4. Re-open PanWriter

**Comment by mb21** [comment]
Ah yes, I think that's a race condition that I've been meaning to fix for some time... it doesn't always happen, right? only sometimes...

**Comment by kris10ansn** [comment]
This happens every time. If i have a window open and open files, without closing all the windows, they will show up in the open recent menu, but if i close the windows the menu is cleared. I have the aur package.

**Comment by kris10ansn** [comment]
Update: installed appimage from the github releases. The open recent menu is empty at first, but if i open a file all the entries appear.

**Comment by mb21** [comment]
Thanks for the update. Yes, this should be fixed as part of a major refactor I'm currently working on in the `ts` branch... but there's still quite a bit of work required...

**Comment by mb21** [comment]
Okay, this should be fixed in 0.8.0, I've published a RC (release candidate) version, that hopefully doesn't have too many other bugs: https://github.com/mb21/panwriter/releases

Happy testing! ;-)
