### ISSUE TITLE
Export fails with pandoc error

### ISSUE THREAD

**Issue by AdamIsrael** [mb21/panwriter#19]
Version: 0.6.3 (AppImage)
Pandoc: 2.5

The error:
```
Failed to Export
Called: pandoc --output /tmp/pandoc-test --to --standalone
```

Steps to reproduce:
1. Open PanWriter
2. Open Markdown document
3. File -> Export
4. Export

**Comment by mb21** [comment]
well... what's the error? also can you try with the newest pandoc version?

**Comment by AdamIsrael** [comment]
Sorry, bad Markdown on my part. I've updated the report.

**Comment by AdamIsrael** [comment]
Installed the latest pandoc -- version 2.9.1 -- and get the same error.

**Comment by mb21** [comment]
huh, I still don't see the error you get....
also: it works for me...

**Comment by AdamIsrael** [comment]
I'll install from source and see if I can a) reproduce the error and b) track down the pandoc error code/message.

**Comment by mb21** [comment]
maybe try the exact same command on the commandline directly? then at least you know whether it's a panwriter thing or a pandoc thing...

**Comment by mb21** [comment]
closing until more info available...
