### ISSUE TITLE
Installer 0.6.3 seems to contain virus WS.reputation.1

### ISSUE THREAD

**Issue by cdwijs** [mb21/panwriter#20]
![ws reputation 1](https://user-images.githubusercontent.com/8469638/76072937-1d093880-5f99-11ea-9041-32d8ccf0d713.png)
![ws reputation 1-details](https://user-images.githubusercontent.com/8469638/76072939-1da1cf00-5f99-11ea-99b1-fcda9d2795aa.png)

https://github.com/mb21/panwriter/releases/download/v0.6.3/panwriter-setup-0.6.3.exe

**Comment by mb21** [comment]
uh, you're sure this is not a false positive? the screenshots don't provide a lot of detail what it thinks is wrong with it...

**Comment by cdwijs** [comment]
This is all the information I have. (This is a company computer that I have limited control over).
Best I can do is to install Clamwin, and do a scan with that.

**Comment by mb21** [comment]
Let me know when you have more info... but this is not actionable for me...
