### ISSUE TITLE
preview pages

### ISSUE THREAD

**Issue by Li-An** [mb21/panwriter#22]
Hello, I am very interested with the pages preview feature and I tried the example 

```
---
title: my document
style :
@page {
size: A4;
margin-top : 2cm;
}
---
```
but it only shows the code.
<img width="1253" alt="2020-05-05_11h54_51" src="https://user-images.githubusercontent.com/689870/81054591-5db4fd80-8ec7-11ea-86d1-71e19f1cfad4.png">

**Comment by mb21** [comment]
that part is YAML... you need to get the indentation right... you can validate e.g. on http://www.yamllint.com/

**Comment by Li-An** [comment]
Sorry, I did not receive the notification for your answer. Thanks. I will take a look.
