### ISSUE TITLE
Make PDF searchable and convert headings to bookmarks

### ISSUE THREAD

**Issue by mike-lowski** [mb21/panwriter#34]
Printing to PDF for some reason converts them as a scan without searchable functions nor bookmarks. Would be nice to have them convert with these features (like it does exporting to pdflatex).

Thanks for your awesome work!

**Comment by mb21** [comment]
Interesting... what's your operating system and version?

If you have `pdflatex` and `pandoc` installed, you can also do File -> Export and choose `PDF` in the dropdown. Depending on your needs you can also set the `pdf-format` YAML metadata key to `html`, `context` or anything else pandoc supports for converting to PDF... see https://github.com/mb21/panwriter#export-via-pandoc

**Comment by mike-lowski** [comment]
Windows 10, I have `pdlatex `and `pandoc `installed. Exporting to pdflatex generates the file with these features, but of course in a latex template. I tried changing the `pdf-format` to `html` but for some reason PanWriter doesn't find `wkhtmltopdf `(I have it installed too).

**Comment by mb21** [comment]
> but for some reason PanWriter doesn't find `wkhtmltopdf`

can you post the output message in the dialog? what happens if you execute `pandoc -t html` etc. directly in a command prompt? What pandoc version have you installed?

**Comment by mb21** [comment]
I just tried on macOS, and after I saved my markdown file, wkhtmltopdf export worked... (exporting from an unsaved file gave me a permissions error... that's probably something I could code a better error message for...)

**Comment by mike-lowski** [comment]
![](https://i.postimg.cc/NF28p379/Capture.png)

When running `pandoc -t html` nothing happens in my cmd.

Pandoc is 2.10.1 last update.

I'll keep trying, for sure it's some silly thing.

**Comment by mb21** [comment]
sorry I meant the full command, you need to include the paths... so something like:

    pandoc --output C:\...\Desktop\test.pdf --to html C:\...\Desktop\yourInputFile.md

**Comment by mike-lowski** [comment]
Same message: wkhtmltopdf not found.

**Comment by mb21** [comment]
then you haven't installed `wkhtmltopdf` in a way pandoc can find it... what happens if you do:

    wkhtmltopdf --version

**Comment by mike-lowski** [comment]
Not recognized as internal or external command.

**Comment by mb21** [comment]
I don't know much about Windows, but must be something with your wkhtmltopdf install... see e.g. https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2971
