### ISSUE TITLE
Feature request: rendering of tables

### ISSUE THREAD

**Issue by Picklejar05** [mb21/panwriter#36]
Hi, I've only used this program for about 30 minutes and I don't use github very often, so sorry if I'm posting this in the wrong place or something. Anyway, I noticed that the document preview doesn't correctly display any tables other than regular pipe tables. Is this going to be fixed? Thanks!

[![all table styles other than regular pipe tables don't work](https://user-images.githubusercontent.com/50224374/93007723-f0724280-f520-11ea-9fbe-88e16e0c93e0.png)](https://pandoc.org/MANUAL.html#tables)

**Comment by mb21** [comment]
Yes, [that's a TODO](https://github.com/mb21/panwriter/#markdown-syntax). Last time I checked, there was no suitable `markdown-it` plugin though...

**Comment by jan-zajic** [comment]
https://github.com/basverweij/markdown-it-gridtables

**Comment by mb21** [comment]
Nice, I'll try to take a look into integrating that into [markdown-it-pandoc ](https://github.com/mb21/markdown-it-pandoc) soonish.. or feel free to make a pull request there if you can get it working without breaking too much else :)

**Comment by mb21** [comment]
I implemented this on master now... guess needs a bit more testing before a release...
