### ISSUE TITLE
Dark Theme desirable

### ISSUE THREAD

**Issue by rtorresca** [mb21/panwriter#37]
I think that a *Dark Theme* will not be a distracting feature and, to me at least, it's much more convenien for long time working. 
Thanks for this usefull editor!
Rafael

**Comment by andreagam** [comment]
Plus 1

**Comment by martyheyman** [comment]
Plus 1 -- as an older user/writer, Dark Themes are much easier on aging eyes.

**Comment by mb21** [comment]
I've added a few commits (https://github.com/mb21/panwriter/commit/6687173680cc69a0ebe740422ba4fca68688ac38 and following)... if you follow https://github.com/mb21/panwriter#develop, you can try it out and let me know what you think... I'll probably make a release soon...

**Comment by mb21** [comment]
Okay, I released dark mode as part of PanWriter 0.7.1
