### ISSUE TITLE
support $$...$$ math mode

### ISSUE THREAD

**Issue by asmwarrior** [mb21/panwriter#4]
Hi, I just test the latest Windows release PanWriter.Setup.0.5.4.exe, it support inline math mode, that is:
`$a+b$`, but it failed in `$$a+b$$` which is another math mode(display the formula in a separate line), can you support it? Thanks.

**Comment by asmwarrior** [comment]
> 
> 
> Are you talking about the preview or export? And if export: to which format?
> 

I'm talking about the preview.

> Either way, it works for me. Make sure there is a blank line before the line with `$$a+b$$`...

OK, if I have a blank line before the `$$a+b$$`, it works as expected.

**Comment by mb21** [comment]
Great! Closing this then...
