### ISSUE TITLE
Feature Request: Add support for -citeproc 

### ISSUE THREAD

**Issue by lukaskawerau** [mb21/panwriter#41]
It would be fantastic if Panwriter supported compiling citations using Pandoc's `-citeproc` option: https://pandoc.org/MANUAL.html#option--citeproc

I have many people that would hugely benefit from using Panwriter in academia, but can't right now because of a lack of this feature.

**Comment by mb21** [comment]
In theory this should already work when you use File -> Export.... using something like this at the top of your file:

```
---
bibliography:
- foobar.bib
---
```

But of course, it won't show up in the preview... because there we don't run pandoc and latex..

**Comment by mb21** [comment]
just tried it myself, this worked for me with pandoc 2.11.0.2:

```
---
output:
  latex:
    citeproc: true
bibliography: myfile.bib
---
```
