### ISSUE TITLE
Pandoc in WebAssembly potentially useful here?

### ISSUE THREAD

**Issue by ickc** [mb21/panwriter#43]
Not a JS/WebAssembly dev here so can't tell: this transpiler here https://github.com/tweag/asterius can transpile pandoc to WebAssembly, which can call pandoc in the browser to convert documents.

So it would mean it can be used here as the rendering engine? Don't know the latency is good enough for live view though.

**Comment by mb21** [comment]
Thanks! I've already opened https://github.com/mb21/panwriter/issues/27 about this... but so far didn't have time to give it a try...

**Comment by ickc** [comment]
I should've read it first. I got sloppy on mobile...
Thanks!
