### ISSUE TITLE
Windows: Clicking on print icon in print preview yields no action

### ISSUE THREAD

**Issue by Hoffenbar** [mb21/panwriter#45]
v0.71 windows:
Nothing happens when clicking on the print icon in the print preview pane.

**Comment by mb21** [comment]
I don't have a windows box around to test... does `File` -> `Print` work?
if not, do you see any error in the dev console (Ctrl-Alt-i)?

**Comment by mb21** [comment]
I just tried PanWriter 0.7.2 on a friend's Windows 10.0 and it worked...?
