### ISSUE TITLE
Exporting to ePub repeats the title

### ISSUE THREAD

**Issue by Parsida** [mb21/panwriter#47]
Hi, 

As you can see in this epub: https://t2188684.p.clickup-attachments.com/t2188684/15afd1f9-3f10-491c-a072-c73e4d3aac89/bigger-leaner-stronger-summary-storyshots.epub the title is repeated twice. Why is that?

This is the markup: 

```
---
title: 'Summary of Bigger Leaner Stronger by Michael Mathews '
author: StoryShots - Free Book Summaries and More
---


## Synopsis

[Bigger Leaner Stronger: The Simple Science of Building the Ultimate Male Body](https://geni.us/bigger-free-audiobook) focuses on the best tips for building muscle and losing fat. Michael Matthews gives you a blueprint for how you can start eating and exercising your way towards a bigger, leaner, and stronger body. He claims this book should offer the advice required to gain 10 to 15 pounds of lean mass in only 8-12 weeks.
```

**Comment by mb21** [comment]
Not sure which two titles you're referring to... perhaps the title page? which eBook viewer do you use?

Also make sure that you use the latest pandoc version and possibly see also https://pandoc.org/epub.html

**Comment by mb21** [comment]
Closing as no further info was provided. If this is still a problem, please ask on the pandoc-discuss mailing list...
