### ISSUE TITLE
Use AppImageUpdate?

### ISSUE THREAD

**Issue by ickc** [mb21/panwriter#48]
which allow the AppImage be updated automatically: https://github.com/AppImage/AppImageUpdate

**Comment by mb21** [comment]
I've included the [electron-updater](https://www.npmjs.com/package/electron-updater)... does AppImageUpdate provide any benefit?

**Comment by ickc** [comment]
Apparently it is the "standard" way to update AppImage. This may help: https://docs.appimage.org/packaging-guide/optional/updates.html?highlight=appimageupdate#using-electron-builder

**Comment by mb21** [comment]
Okay... I'm open to merging a pull request that does this... but I don't have a Linux box ready to test...

**Comment by ickc** [comment]
It's ok, you don't have to support this. It was just a suggestion.

**Comment by mb21** [comment]
Okay :-) I'd be happy to support more packaging options, but yeah... really don't have the time to implement and test this for all different kinds of packaging things out there..
