### ISSUE TITLE
Dark theme on macOs Big Sur

### ISSUE THREAD

**Issue by doctormee** [mb21/panwriter#51]
I don't quite know why, but in macOs Dark mode PanWriter looks **Horrible**:
1. Something breaks in highlighting
2. When it automatically switches from Light mode to Dark mode, you have to restart pan writer, otherwise opened preview field is kinda tinted/faded (couldn't catch the moment, so can't exactly repro, except wait for another sundown)

Probably, there's a neat fix I just can't find, but, since there is no 'Preferences' pane in the app I'm finding it hard to fix it on my own. 
The app could benefit from _some_ sort of 'Preferences', like highlight colour options for dark/light mode.
![Screenshot 2021-03-21 at 19 17 45](https://user-images.githubusercontent.com/3170764/111912325-1fdaac80-8a7a-11eb-8156-bacfbd022234.png)

Using macOS Big Sur 11.2.2 and PanWriter 0.7.2

**Comment by mb21** [comment]
Thanks for the report.

1.) I've pushed a commit: should be fixed in https://github.com/mb21/panwriter/commit/7ad0b9a29d4246935dd20f2e75367adb77ce1f19
2.) probably some flakiness in electron or macOS....? I'll try to make a release with the latest electron soonish...

yeah, preferences (or at least a json file to set some customization) are on the todo list ;-)

**Comment by mb21** [comment]
Hopefully this is fixed in 0.8.0 ? https://github.com/mb21/panwriter/releases

(btw. you don't have to wait for night to switch to dark mode.. .you can switch manuall in macOS's "System Preferences" -> General -> Appearance)

**Comment by doctormee** [comment]
The funny thing is that it ONLY occurred when the theme switched automatically — not after a manual switch

Will see if it's fixed in 0.8.0 and get to you

**Comment by mb21** [comment]
Please let me know if you can still reproduce this, but it's probably fixed now...
