### ISSUE TITLE
Can not export 

### ISSUE THREAD

**Issue by welpdx** [mb21/panwriter#54]
## Issue
When exporting a .md file (for e.g., to word .docx), nothing happens. 

Console shows [this](https://i.imgur.com/26u34zt.jpg). When browsing the Roaming folder, PanWriterUserData folder [does not exist](https://i.imgur.com/Cxh3o7n.jpg). 

[md file](https://github.com/welpdx/Extraneous/blob/master/Summary.md) used.

Is there something I am doing wrong? Thanks!

## Other Info

System: Windows 10 Enterprise 2016 LTSB
PanWrite Version: 0.7.2.0 ("Only for me")

**Comment by mb21** [comment]
Hm.. I think the warning is expected if you haven't put a file there on purpose... but the error is not.

Have you installed pandoc for windows? https://pandoc.org/installing.html

**Comment by welpdx** [comment]
Hi @mb21, thanks for your help! I didn't know that Pandoc was an requirement for PanWriter. I had just thought that PanWriter was just built on Pandoc and that no other installations were needed for PanWriter to work lol. 🤦‍

After installing Pandoc, [export was an success](https://i.imgur.com/5xnnEZz.jpg)!

---

Btw, is there a way to remove the [square brackets around heading section](https://i.imgur.com/oQloTkk.jpg) after export? Many Thanks!

**Comment by mb21** [comment]
👍 There should be an error message when pandoc is not installed, I'll try to fix that...

> Btw, is there a way to remove the square brackets around heading section after export? 

I don't get those with the md file you linked to above?

**Comment by welpdx** [comment]
> 👍 There should be an error message when pandoc is not installed, I'll try to fix that...

That is a great idea! If adding that error message is too much trouble, it might be quick to simply add a Requirement section in the readme. :D 


> I don't get those with the md file you linked to above?

Hmm, weird. Oh well, it's not a big deal. I'll report back if anything changes. Thank you again for your help.

**Comment by mb21** [comment]
Good point, I've added something to the README...

**Comment by welpdx** [comment]
> Good point, I've added something to the README...

Nice!

Also, in regards to the square brackets, it apparently has something to do with my Word processor, not PanWriter. It doesn't appear in printing either, so it a very very minor issue. 

Thanks again for all your help and for you amazing PanWriter tool! It is absolutely my fav and my goto rn.
