### ISSUE TITLE
Default color of chinese character seems light

### ISSUE THREAD

**Issue by Serenade600** [mb21/panwriter#56]
The default color of chinese character on the left editor seems too light to easily recognise. Is there some way to change its color as the right preview part does？

![light_font](https://user-images.githubusercontent.com/40297752/113381345-4de0ba80-93b1-11eb-8c93-f74bb30b617d.jpg)

**Comment by Serenade600** [comment]
> 
> 
> The default color of chinese character on the left editor seems too light to easily recognise. Is there some way to change its color as the right preview part does？
> 
> ![light_font](https://user-images.githubusercontent.com/40297752/113381345-4de0ba80-93b1-11eb-8c93-f74bb30b617d.jpg)

On Win10. The latest version of panwriter.

**Comment by Serenade600** [comment]
On Win10. The latest version of panwriter.

**Comment by mb21** [comment]
Can you post the text you have in the screenshot as text here?

**Comment by Serenade600** [comment]
Here you go.

> # Text
>This is a text.
>这里是中文。

**Comment by mb21** [comment]
Thanks! hm.. cannot reproduce this on macOS 11.2.3

<img width="998" alt="image" src="https://user-images.githubusercontent.com/157497/113415604-db2b0b80-93bf-11eb-95dc-8108061f3289.png">

My best guess is that the font or the font rendering is different on Windows. But I'm neither very familiar with Chinese nor Windows 😅 

If you know a bit of CSS, perhaps you can fix it by opening `View` menu -> `Toggle Developer Tools` and set a different font-family or other CSS property..?

(I'll also try to merge the `ts` branch soon, which includes an updated version of Electron... but not sure that would fix it..)

**Comment by mb21** [comment]
I just tried the newest PanWriter release and this seems to have been fixed.

![image](https://user-images.githubusercontent.com/157497/148068307-5b122513-db07-4fa8-bf57-b6b85d9f00e4.png)
