### ISSUE TITLE
Does panwriter support pandoc-crossref?

### ISSUE THREAD

**Issue by pykong** [mb21/panwriter#68]
Thanks for putting up this project!

A short question: Does panwriter support [pandoc-crossref](https://github.com/lierdakil/pandoc-crossref)?
Will the preview properly render the references?

Thanks!

**Comment by mb21** [comment]
Hello! no, the preview only runs markdown-it.js with a few plugins, not the whole of pandoc. Otherwise it would be quite slow...

**Comment by pykong** [comment]
@mb21 Thank you, for the answer!
