### ISSUE TITLE
Updater minor issue: Uninstalled panwriter but did not install new version

### ISSUE THREAD

**Issue by welpdx** [mb21/panwriter#87]
### Process
While using Panwriter today, I got a message about an update letting me know that an update is downloading and will install after I close the window. I was pleasantly surprised. I worked on my .md file for half an hour and closed panwriter.

After a moment, a "old_uninstaller" ran and asked for admin permission UAC, which I allowed. Then nothing happened. Pandoc seemed to have uninstalled but the newer version was not installed. 

### Expected result
Expected it to uninstall and install new version.

### Current result
Pandoc seemed to have uninstalled but the newer version was not installed. 

### Other info
Windows 10 Pro 21H1
Panwriter 0.8.1 (was the version with the updater, I think)

---

Just fyi. It's a very very minor issue. 

Also, Merry Christmas mb21! I'm stoked that you are still working on this. On the holidays no less!

Welp

**Comment by mb21** [comment]
Thanks for the report and the kind words!

Hm... I don't have a windows install right now to test... can you reproduce it by installing an old version from https://github.com/mb21/panwriter/releases and starting it up with the commandline? does it print any error message there?

for what it's worth, I'm using [electron-updater](https://www.npmjs.com/package/electron-updater), but couldn't find any issues there that mention this behaviour on windows...

**Comment by mb21** [comment]
We've an updated electron-updater in PanWriter 0.8.3, let me know if it's still happening on windows, then we can reopen the issue. But I just auto-updated successfully from 0.8.2 on macOS.

**Comment by welpdx** [comment]
Update: I downloaded PanWriter V0.8.1 and the update to v0.8.3 worked as smooth as melted butter in a frying Pan!
Started the exe with commandline and it downloaded update, indicated that it will install silently, and installed after I closed PanWriter. Idk y it shows old_uninstaller and didn't work when I first tried it.

<details>
<summary><mark><font color=darkred>cmd output text</font></mark>
</summary>
<p>

```cmd


C:\WINDOWS\system32>cd C:\Program Files\PanWriter

C:\Program Files\PanWriter>start PanWriter.exe

C:\Program Files\PanWriter>
Checking for update
no recentFiles found? [Error: ENOENT: no such file or directory, open 'C:\Users\welpdx\AppData\Roaming\PanWriter\recentFiles.json'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\welpdx\\AppData\\Roaming\\PanWriter\\recentFiles.json'
}
Found version 0.8.3 (url: PanWriter-Setup-0.8.3.exe)
Downloading update from PanWriter-Setup-0.8.3.exe
updater cache dir: C:\Users\welpdx\AppData\Local\panwriter-updater
Download block maps (old: "https://github.com/mb21/panwriter/releases/download/v0.8.1/PanWriter-Setup-0.8.1.exe.blockmap", new: https://github.com/mb21/panwriter/releases/download/v0.8.3/PanWriter-Setup-0.8.3.exe.blockmap)
File has 4577 changed blocks
[
  {
    "kind": 1,
    "start": 0,
    "end": 119515
  },
  {
    "kind": 0,
    "start": 111323,
    "end": 184098
  },
  {
    "kind": 1,
    "start": 192290,
    "end": 284676
  },
  {
    "kind": 0,
    "start": 274946,
    "end": 307714
  },
  {
    "kind": 1,
    "start": 317444,
    "end": 6895578
  },
  {
    "kind": 0,
    "start": 6637239,
    "end": 6668643
  },
  {
    "kind": 1,
    "start": 6926982,
    "end": 6946267
  },
  {
    "kind": 0,
    "start": 6687928,
    "end": 6720696
  },
  {
    "kind": 1,
    "start": 6979035,
    "end": 8045212
  },
  {
    "kind": 0,
    "start": 8018756,
    "end": 8032514
  },
  {
    "kind": 1,
    "start": 8058970,
    "end": 8080549
  },
  {
    "kind": 0,
    "start": 8054093,
    "end": 8090928
  },
  {
    "kind": 1,
    "start": 8117384,
    "end": 8385816
  },
  {
    "kind": 0,
    "start": 8379407,
    "end": 8394328
  },
  {
    "kind": 1,
    "start": 8400737,
    "end": 8424632
  },
  {
    "kind": 0,
    "start": 8418223,
    "end": 8451804
  },
  {
    "kind": 1,
    "start": 8458213,
    "end": 8478709
  },
  {
    "kind": 0,
    "start": 8472300,
    "end": 8502347
  },
  {
    "kind": 1,
    "start": 8508756,
    "end": 8522442
  },
  {
    "kind": 0,
    "start": 8516033,
    "end": 8529888
  },
  {
    "kind": 1,
    "start": 8536297,
    "end": 96099330
  },
  {
    "kind": 0,
    "start": 81604581,
    "end": 81836013
  },
  {
    "kind": 1,
    "start": 96330762,
    "end": 96418082
  },
  {
    "kind": 0,
    "start": 81920227,
    "end": 81935853
  },
  {
    "kind": 1,
    "start": 96433708,
    "end": 96608043
  }
]
Full: 94,343.79 KB, To download: 93,797.14 KB (99%)
Differential download: https://github.com/mb21/panwriter/releases/download/v0.8.3/PanWriter-Setup-0.8.3.exe
download range: bytes=0-119514
Redirect to https://objects.githubusercontent.com/github-production-release-asset-2e65be/155992061/2ef4895b-face-4421-8f31-9ccddfbdd4ff
download range: bytes=192290-284675
download range: bytes=317444-6895577
download range: bytes=6926982-6946266
download range: bytes=6979035-8045211
download range: bytes=8058970-8080548
download range: bytes=8117384-8385815
download range: bytes=8400737-8424631
download range: bytes=8458213-8478708
download range: bytes=8508756-8522441
download range: bytes=8536297-96099329
download range: bytes=96330762-96418081
download range: bytes=96433708-96608042
New version 0.8.3 has been downloaded to C:\Users\welpdx\AppData\Local\panwriter-updater\pending\PanWriter-Setup-0.8.3.exe
Auto install update on quit
Install: isSilent: true, isForceRunAfter: false


```

</p>
</details>

Thanks @mb21 . Sorry I didn't get back to you sooner.

Welp

**Comment by mb21** [comment]
that's great to hear, thanks!
