### ISSUE TITLE
Text input indicator disappears

### ISSUE THREAD

**Issue by GitBruno** [mb21/panwriter#9]
1. Type a paragraph
2. Click inside the paragraph
> Text input indicator missing

**Comment by mb21** [comment]
Curious, I cannot reproduce this on macOS 10.14.3. What platform are you on?

**Comment by GitBruno** [comment]
Same MacOS 10.14.3

But I forgot to mention that I work in split view :)

**Comment by mb21** [comment]
Ah, you're clicking on the paragraph in the preview? Yes, then the cursor disappears. Never thought about it, but yes, that could be changed...

**Comment by GitBruno** [comment]
I am on the editing side. But yes, that would be nice. 👍 

I did not realise my view was not 100% 
Setting `View > Actual Size` __fixed__ the problem. (Huge type! Would be good to have a font pref)

Back to the problem:

Zoom out twice (2, 5, 7, 9,11 or more) and the input indicator disappears.

**Comment by mb21** [comment]
This has probably something to do with the codemirror editor losing focus...

**Comment by mb21** [comment]
Okay, zooming out now doesn't make the cursor disappear anymore... so I guess this bug can be closed?

(clicking the preview still does... but I don't think there's any reasonable way to change that in an electron app, which wouldn't break other things... an also many native apps behave this way..)
