### ISSUE TITLE
Home/End keys go to beginning & end of paragraph, not the current line

### ISSUE THREAD

**Issue by lproven** [mb21/panwriter#99]
I find it frustrating not to be able to go straight to the start and end of the current line.

For reference, I am running the AppImage on fully-updated Ubuntu 21.10, using the Unity desktop. This behaviour has persisted since v0.8.2.

I expect `Home` and `End` to behave as in other Linux or Windows GUI editors: to go to the first position in the current line, or to the end of it, respectively. As it is, they jump to the beginning or end of the paragraph, which may be several on-screen lines away. I wonder, but have no way to tell, if it is jumping to the beginning and end of the underlying plain-text Markdown line.

**Comment by mb21** [comment]
> I wonder, but have no way to tell, if it is jumping to the beginning and end of the underlying plain-text Markdown line.

yes, that's precisely what's happening. you can verify this by introducing a newline in your paragraph: it will jump to there.

on macOS, I can jump to start/end of the visual line with `CMD-left/right`. On Windows it might be `ALT-left/right`, see https://defkey.com/codemirror-shortcuts
